name: c:\Users\mihir\Research\Gallant Lab\Optical-Flow-Encoding\.conda
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - aom=3.9.1=he0c23c2_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - dav1d=1.2.1=hcfcfb64_0
  - eigen=3.4.0=h477610d_1
  - expat=2.7.1=h8ddb27b_0
  - ffmpeg=6.1.1=hc79a5da_3
  - fontconfig=2.15.0=h765892d_1
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.14.1=h57928b3_0
  - gflags=2.2.2=he0c23c2_1005
  - glog=0.5.0=h4797de2_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=h1f81b68_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - jpeg=9e=hcfcfb64_3
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.3.0=he916da2_2
  - libavif16=1.3.0=he916da2_2
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkrb5=1.21.3=h885b0b7_4
  - libogg=1.3.5=h2466b09_1
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h7351971_1
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=he9d8c4a_0
  - libtheora=1.1.1=hc70643c_1006
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.4=hfa2b4ca_0
  - mkl=2025.3.0=hac47afa_454
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - mysql-common=9.3.0=h2224204_0
  - mysql-libs=9.3.0=h809f9c2_0
  - numpy=2.3.4=py312hc2e1e29_0
  - numpy-base=2.3.4=py312hc851d2b_0
  - opencv=4.12.0=py312h6fcf9f4_0
  - openssl=3.5.4=h725018a_0
  - pcre2=10.46=h3402e2f_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h5112557_1
  - python=3.12.12=h716150d_1
  - qtbase=6.9.2=h06bae2a_4
  - rav1e=0.7.1=ha073cba_3
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=hbeecb71_2
prefix: c:\Users\mihir\Research\Gallant Lab\Optical-Flow-Encoding\.conda
