name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends
  - python=3.12
  - setuptools
  - pip
  - wheel
  - anaconda-anon-usage
  - anaconda-catalogs
  - anaconda-client
  - anaconda-project
  - anaconda-navigator=2.7.0
  - conda=25.9.1
  - conda-build
  - conda-content-trust
  - conda-libmamba-solver
  - conda-pack
  - conda-package-handling
  - conda-package-streaming
  - conda-token
  - console_shortcut
  - powershell_shortcut
  - anaconda-toolbox
  - libmamba
  - libmambapy
  - opencv
prefix: C:\Users\mihir\anaconda3
